#!/bin/bash
set -e

d=`pwd`

cd ~/.local/share/latex/school
git pull
cd ~/.local/share/latex/school-personal
git pull
cd "$d"

cd $1
git pull
tek
make
tar -cv `find -iname "*.pdf"` | tar -xC ~/public_html/school
cd "$d"

chmod oug+rX -R ~/public_html/school
