#!/bin/bash

if [[ "$(hostname)" != "berkeley.dabbelt.com" ]]
then
    ssh berkeley.dabbelt.com /home/palmer/public_html/cgi-bin/newmovies
    exit $?
fi

echo -e "Content-type: text/html\r\n\r\n"

echo "<html>"
echo "<head>"
echo "<title>New Movies</title>"
echo "</head>"

echo "<body>"

echo "<pre>"

echo "<b>/home/media/video:</b>"
cd /home/media/video
find * -type f -print0 \
    | xargs -0 stat --format '%Y :%y %n' \
    | sort -nr \
    | cut -d: -f2- \
    | cut -d' ' -f4-
find * -type l -print0 \
    | xargs -0 stat --format '%Y :%y %n' \
    | sort -nr \
    | cut -d: -f2- \
    | cut -d' ' -f4- \
    | head -n30

echo ""
echo ""

echo "<b>/home/media/scratch:</b>"
cd /home/media/scratch
find * -type f -maxdepth 1 -print0 \
    | xargs -0 du -h

echo ""
echo ""

echo "<b>media@privatelayer.dabbelt.com:</b>"
ssh media@privatelayer.dabbelt.com "transmission-remote -t all -l"

echo ""
echo ""

date

echo "</pre>"

echo "</body>"

echo "</html>"
