#!/bin/bash

echo -e "Content-type: text/html\r\n\r\n"

echo "<html>"
echo "<head>"
echo "<title>New Movies</title>"
echo "</head>"

echo "<body>"

echo "<pre>"
cd /home/media/video
find * -type f -print0 \
    | xargs -0 stat --format '%Y :%y %n' \
    | sort -nr \
    | cut -d: -f2- \
    | cut -d' ' -f4-
find * -type l -print0 \
    | xargs -0 stat --format '%Y :%y %n' \
    | sort -nr \
    | cut -d: -f2- \
    | cut -d' ' -f4- \
    | head -n30

echo ""
echo ""

cd /home/media/scratch
find * -type f -maxdepth 1 -print0 \
    | xargs -0 du -h
echo "</pre>"

echo "</body>"

echo "</html>"
